import { Metadata } from "next";

/**
 * Generate SEO-optimized metadata for different QR code types
 */
export function generateQRTypeSEO(type: string): Partial<Metadata> {
  const baseTitle = "AirQR - Free Lightweight QR Generator";
  const baseDomain = "https://airqr.vercel.app";

  const typeConfigs = {
    wifi: {
      title: `${baseTitle} | WiFi QR Codes - Share Network Access Instantly`,
      description:
        "Generate secure WiFi QR codes instantly. Share network access without revealing passwords. Privacy-first WiFi QR generator - no data collection, works offline.",
      keywords: [
        "WiFi QR code",
        "network sharing QR",
        "WiFi password QR",
        "wireless network QR",
        "secure WiFi sharing",
      ],
    },
    vcard: {
      title: `${baseTitle} | vCard QR Codes - Digital Business Cards`,
      description:
        "Create digital business card QR codes instantly. Share contact information with vCard QR codes. Professional networking made simple and private.",
      keywords: [
        "vCard QR code",
        "digital business card",
        "contact QR code",
        "business card QR",
        "networking QR",
      ],
    },
    url: {
      title: `${baseTitle} | URL QR Codes - Link Sharing Made Easy`,
      description:
        "Generate URL QR codes for instant link sharing. Convert any web link into a scannable QR code. Perfect for marketing, events, and quick access.",
      keywords: [
        "URL QR code",
        "link QR code",
        "website QR",
        "web link sharing",
        "marketing QR code",
      ],
    },
    text: {
      title: `${baseTitle} | Text QR Codes - Share Any Text Instantly`,
      description:
        "Create text QR codes for messages, notes, and information sharing. Convert any text into a scannable QR code quickly and privately.",
      keywords: [
        "text QR code",
        "message QR",
        "note QR code",
        "text sharing QR",
        "information QR",
      ],
    },
  };

  const config =
    typeConfigs[type as keyof typeof typeConfigs] || typeConfigs.text;

  return {
    title: config.title,
    description: config.description,
    keywords: [
      ...config.keywords,
      "free QR generator",
      "privacy QR",
      "lightweight QR",
      "fast QR generator",
    ],
    openGraph: {
      title: config.title,
      description: config.description,
      url: baseDomain,
      type: "website",
    },
    twitter: {
      title: config.title,
      description: config.description,
      card: "summary_large_image",
    },
  };
}

/**
 * Generate structured data for different QR code functionalities
 */
export function generateQRStructuredData() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "AirQR",
    applicationCategory: "UtilityApplication",
    operatingSystem: "Web Browser",
    description:
      "Free lightweight QR code generator with privacy-first design. Generate WiFi, vCard, URL, and text QR codes instantly.",
    url: "https://airqr.vercel.app",
    screenshot: "https://airqr.vercel.app/android-chrome-512x512.png",
    featureList: [
      "WiFi QR Code Generation",
      "vCard Contact QR Codes",
      "URL Link QR Codes",
      "Text Message QR Codes",
      "Privacy-First Design",
      "Offline Functionality",
      "Zero Data Collection",
      "Lightning Fast Generation",
      "Mobile Responsive Design",
      "High-Resolution Downloads",
    ],
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    },
    author: {
      "@type": "Person",
      name: "Muhammad Muzammil",
      url: "https://m-muzammil.vercel.app",
    },
    publisher: {
      "@type": "Person",
      name: "Muhammad Muzammil",
    },
    datePublished: "2025-01-01",
    dateModified: new Date().toISOString().split("T")[0],
    version: "1.0.0",
    browserRequirements: "Modern web browser with JavaScript enabled",
    softwareHelp: {
      "@type": "CreativeWork",
      url: "https://airqr.vercel.app",
    },
  };
}

/**
 * SEO-optimized alt text generator for QR codes
 */
export function generateQRAltText(type: string, content?: string): string {
  const typeDescriptions = {
    wifi: "WiFi network QR code for secure wireless connection",
    vcard: "vCard contact information QR code for digital business card",
    url: "URL link QR code for instant website access",
    text: "Text message QR code for information sharing",
  };

  const baseAlt =
    typeDescriptions[type as keyof typeof typeDescriptions] || "QR code";

  if (content && content.length < 50) {
    return `${baseAlt} containing: ${content}`;
  }

  return `${baseAlt} generated by AirQR - Privacy-first QR generator`;
}

/**
 * Generate SEO-friendly QR code filenames
 */
export function generateSEOFilename(type: string, size: number): string {
  const timestamp = new Date().toISOString().split("T")[0];
  return `airqr-${type}-qrcode-${size}x${size}-${timestamp}.png`;
}

/**
 * Meta tags for better social media sharing
 */
export function generateSocialMetaTags(type?: string) {
  const typeSpecific = type ? ` | ${type.toUpperCase()} QR Codes` : "";

  return {
    "og:site_name": "AirQR",
    "og:type": "website",
    "og:locale": "en_US",
    "twitter:site": "@muzammil_shayk",
    "twitter:creator": "@muzammil_shayk",
    "twitter:card": "summary_large_image",
    "article:author": "Muhammad Muzammil",
    "article:publisher": "Muhammad Muzammil",
    "application-name": `AirQR${typeSpecific}`,
    "msapplication-tooltip": "Free Privacy-First QR Code Generator",
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": "AirQR",
  };
}
