const QRCode = require('qrcode');

async function verify() {
    const formattedData = 'test';
    const colorDark = '#000000';
    const margin = 4;

    let svgString = await QRCode.toString(formattedData, {
        type: 'svg',
        margin: margin,
        color: {
            dark: colorDark,
            light: '#ffffff',
        },
        errorCorrectionLevel: 'H',
    });

    const watermarkText = 'Generated by AirQR';
    const svgEndIndex = svgString.lastIndexOf('</svg>');
    if (svgEndIndex !== -1) {
        const viewBoxMatch = svgString.match(/viewBox="0 0 (\d+) (\d+)"/);
        let x = "98%";
        let y = "98%";
        let fontSize = "8";

        if (viewBoxMatch) {
            const width = parseInt(viewBoxMatch[1]);
            const height = parseInt(viewBoxMatch[2]);
            fontSize = Math.max(0.5, width / 32);
            x = width - (width / 60);
            y = height - (height / 60);
            console.log(`ViewBox: ${width}x${height}`);
            console.log(`Calculated: x=${x}, y=${y}, fontSize=${fontSize}`);
        }

        const watermarkSvg = `  <text x="${x}" y="${y}" font-family="Arial, sans-serif" font-size="${fontSize}" fill="${colorDark}" opacity="0.5" text-anchor="end">${watermarkText}</text>\n`;
        svgString = svgString.slice(0, svgEndIndex) + watermarkSvg + svgString.slice(svgEndIndex);
        console.log('Final SVG Text Element:');
        console.log(watermarkSvg.trim());
    }
}

verify();
